version: '3.9'

services:
  elasticsearch:
    container_name: elasticsearch
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.4
    environment:
      - discovery.type=single-node
    ports:
      - "9200:9200"
      - "9300:9300"
    volumes:
      - elasticsearch:/usr/share/elasticsearch/data
    networks:
      - elk_network
  kibana:
    container_name: kibana
    image: docker.elastic.co/kibana/kibana:7.17.4
    environment:
      ELASTICSEARCH_HOSTS: "http://elasticsearch:9200"
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch
    networks:
      - elk_network
  logstash:
    container_name: logstash
    image: docker.elastic.co/logstash/logstash:7.17.4
    ports:
      - "4560:4560"
    volumes:
      - ./logstash.conf:/usr/share/logstash/pipeline/logstash.conf
    networks:
      - elk_network

networks:
  elk_network:
    external:
      name: nivorbit_services_nw

volumes:
  elasticsearch: