version: '3.9'

services:
  auth-server:
    container_name: auth-server
    image: nivorbit/services/keycloak-server:1.0.0
    command: ["start-dev", "--proxy", "edge"]
    ports:
      - "8888:8080"
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=change_me
#    volumes:
#      - auth:/opt/keycloak/data
    networks:
      - services_network
  customer-service:
    container_name: customer-service
    image: nivorbit/services/customer-service
    ports:
      - "8081:8080"
    networks:
      - services_network
  fraud-service:
    container_name: fraud-service
    image: nivorbit/services/fraud-service
    ports:
      - "8082:8080"
    networks:
      - services_network
#  api-gateway:
#    container_name: api-gateway
#    image: nivorbit/services/api-gateway
#    ports:
#      - "8083:8080"
#    networks:
#      - services_network


networks:
  services_network:
    name: nivorbit_services_nw
    driver: bridge

volumes:
  auth:
